home/urls.py
from django.urls import path, include
from .views import home_index

urlpatterns = [
    path('', home_index, name='home-index'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('board/', include('board.urls')),
    path('misc/', include('misc.urls')),
    path('libraries/', include('libraries.urls')),
    path('books/', include('books.urls')),
    path('clubs/', include('clubs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('my_profile/<str:username>', views.my_profile, name='user_profile'),
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.logout_user, name='logout'),
    path('register_user/', views.register_user, name='register'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_books/', views.my_books, name='user_books'),
    path('my_books/add/<str:reference>', views.add_overdue, name='add_overdue'),
    path('my_books/giveback/<str:reference>', views.edit_overdue, name='edit_overdue'),
    path('my_clubs/', views.my_clubs, name='user_clubs'),
    path('my_clubs/join/<int:club_id>', views.join_club, name='join_club'),
    path('my_clubs/leave/<int:club_id>', views.leave_club, name='leave_club'),
    path('my_sessions/join/<int:session_id>', views.join_session, name='join_session'),
    path('my_sessions/leave/<int:session_id>', views.leave_session, name='leave_session'),

    path('my_library/', views.my_library, name='user_library'),
    path('informations/', views.informations, name='informations'),
    path('add_book/', views.add_book, name='add_book'),

    path('clubs/<int:club_id>', views.show_club, name='show_club'),
    path('clubs/add', views.add_club, name='add_club'),

    path('members/delete/<int:member_id>', views.delete_member, name='delete_member'),

    path('sessions/<int:session_id>', views.show_session, name='show_session'),
    path('sessions/<int:club_id>/add', views.show_session, name='add_session'),
    path('sessions/<int:session_id>/delete', views.delete_session, name='delete_session'),

    path('participants/delete/<int:participant_id>', views.delete_participant, name='delete_participant')
]

members/models.py
from django.db import models

# Create your models here.

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.db import IntegrityError
from books.models import Book, Overdue
from libraries.models import Library, Bookseller
from clubs.models import Club, Session, Member, Participant
from books.models import Book, Author, Collection, Editor, Overdue, Category, Library, Overdue
from books.forms import AddBookForm
from clubs.forms import AddClubForm, AddSessionForm
import datetime, random, json
from django.utils import timezone

def my_profile(request, username):
    try:
        user = User.objects.get(username=username)
        context = {'user': user}
        return render(request, 'my_profile/index.html', context)
    except:
        return redirect('home-index')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Vous êtes connecté')
            return redirect('members:dashboard')
        else:
            messages.error(request, 'Le pseudo ou le mot de passe est incorrect')
    return render(request, 'authenticate/login.html')

def logout_user(request):
    logout(request)
    return redirect('members:login')

def register_user(request):
    try :
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            user = User.objects.create_user(username, email, password)
            user.save()
            return redirect('members:login')
    except IntegrityError:
        messages.error(request, 'Le nom de compte existe déjà')
    except :
        messages.error(request, 'Une erreur est survenue')
    context = {}
    return render(request, 'authenticate/register.html', context)

def dashboard(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            bookseller = Bookseller.objects.get(user=request.user)
            library = Library.objects.get(id=bookseller.library.id)
            overdues = Overdue.objects.filter(library=library)
            overdues_late = overdues.filter(due_date__lt=timezone.now())
            overdues_in_calendar = []
            for overdue in overdues:
                date = overdue.due_date
                overdues_in_calendar.append({
                    'title': overdue.book.title,
                    'start': date.isoformat(),
                    'end': date.isoformat(),
                    'url': '/books/detail_book/' + str(overdue.book.pk)
            })

            clubs = Club.objects.filter(library=library)
            for club in clubs:
                club.members_count = Member.objects.filter(club=club).count()
            books = []
            for overdue in overdues:
                books.append(overdue.book)
            context = {
                'library': library,
                'books': books,
                'overdues': overdues,
                'overdues_late': overdues_late,
                'overdues_in_calendar': json.dumps(overdues_in_calendar),
                'clubs': clubs
            }
            return render(request, 'dashboard/bookseller.html', context)
        else:
            overdues = Overdue.objects.filter(user=request.user)
            overdues_late = overdues.filter(due_date__lt=timezone.now())

            overdues_in_calendar = []
            for overdue in overdues:
                date = overdue.due_date
                overdues_in_calendar.append({
                    'title': overdue.book.title,
                    'start': date.isoformat(),
                    'end': date.isoformat(),
            })

            members = Member.objects.filter(user=request.user)
            clubs = []
            for member in members:
                clubs.append(member.club)

            sessions = Session.objects.filter(club__in=clubs)
            sessions_in_calendar = []
            for session in sessions:
                end = session.date + datetime.timedelta(hours=1)
                sessions_in_calendar.append({
                    'title': session.club.name,
                    'start': session.date.isoformat(),
                    'end': end.isoformat(),
                })

            context = {
                'overdues_late': overdues_late,
                'overdues_in_calendar': json.dumps(overdues_in_calendar),
                'sessions_in_calendar': json.dumps(sessions_in_calendar)
            }
            return render(request, 'dashboard/user.html', context)
    else:
        return redirect('members:login')

######################################### USERS #########################################

def my_books(request):
    overdues = Overdue.objects.filter(user=request.user)
    overdues_late = overdues.filter(due_date__lt=timezone.now())
    
    context = {
        'overdues': overdues,
        'overdues_late': overdues_late
    }

    return render(request, 'my_book/index.html', context)

def add_overdue(request, reference):
    try :
        overdue = Overdue.objects.get(reference=reference)
        overdue.loan_date = datetime.datetime.now()
        overdue.due_date = datetime.datetime.now() + datetime.timedelta(days=7)
        overdue.status = 'Indisponible'
        overdue.user = User.objects.get(id=request.user.id)
        overdue.save()
        messages.success(request, 'Le livre a été emprunté')
    except :
        messages.error(request, 'Le livre n\'a pas été emprunté')
    return redirect('books:books')
    
def edit_overdue(request, reference):
    try :
        overdue = Overdue.objects.get(reference=reference)
        overdue.status = 'Disponible'
        overdue.user = None
        overdue.save()
        messages.success(request, 'Le livre a été rendu')
    except :
        messages.error(request, 'Le livre n\'a pas été rendu')
    return redirect('members:user_books')

def my_clubs(request):
    members = Member.objects.filter(user=request.user)
    clubs = []
    for member in members:
        clubs.append(member.club)
        
    for club in clubs:
        club.members_count = Member.objects.filter(club=club).count()

    participants = Participant.objects.filter(user=request.user)
    sessions = []
    for participant in participants:
        sessions.append(participant.session)

    context = {
        'clubs': clubs,
        'sessions': sessions
    }
    return render(request, 'my_club/index.html', context)

def join_club(request, club_id):
    try :
        club = Club.objects.get(id=club_id)
        member = Member(club=club, user=request.user)
        member.save()
        messages.success(request, 'Vous avez rejoint le club ' + club.name)
    except :
        messages.error(request, 'Vous n\'avez pas rejoint le club' + club.name)
    return redirect('members:user_clubs')

def leave_club(request, club_id):
    try :
        club = Club.objects.get(id=club_id)
        member = Member.objects.get(club=club, user=request.user)
        member.delete()
        sessions = Session.objects.filter(club=club)
        for session in sessions:
            try:
                participant = Participant.objects.get(session=session, user=request.user)
                participant.delete()
            except:
                pass
        messages.success(request, 'Vous avez quitté le club ' + club.name)
    except :
        messages.error(request, 'Vous n\'avez pas quitté le club' + club.name)
    return redirect('members:user_clubs')

def join_session(request, session_id):
    try :
        session = Session.objects.get(id=session_id)
        participant = Participant(session=session, user=request.user)
        participant.save()
        messages.success(request, 'Vous avez rejoint la session')
    except :
        messages.error(request, 'Vous n\'avez pas rejoint la session')
    return redirect('members:user_clubs')

def leave_session(request, session_id):
    try :
        session = Session.objects.get(id=session_id)
        participant = Participant.objects.get(session=session, user=request.user)
        participant.delete()
        messages.success(request, 'Vous avez quitté la session')
    except :
        messages.error(request, 'Vous n\'avez pas quitté la session')
    return redirect('members:user_clubs')

######################################### BOOKSELLER #########################################

def my_library(request):
    bookseller = Bookseller.objects.get(user=request.user)
    library = Library.objects.get(id=bookseller.library.id)
    overdues = Overdue.objects.filter(library=library)
    clubs = Club.objects.filter(library=library)
    for club in clubs:
        club.members_count = Member.objects.filter(club=club).count()
    books = []
    for overdue in overdues:
        book = Book.objects.get(id=overdue.book.id)
        books.append(book)

    context = {
        'books': books,
        'clubs': clubs,
    }
    return render(request, 'my_library/index.html', context)

def informations(request):
    authors = Author.objects.all()
    editors = Editor.objects.all()
    collections = Collection.objects.all()
    categories = Category.objects.all()
    context = {
        'authors': authors,
        'editors': editors,
        'collections': collections,
        'categories': categories
    }
    return render(request, 'my_library/informations.html', context)

def random_reference():
    return random.randint(100000, 999999)

def get_reference():
    reference = random_reference()
    if Overdue.objects.filter(reference=reference).exists():
        return get_reference()
    else:
        return reference

def add_book(request):
    form = AddBookForm(request.FILES or None)

members/templates/my_library/add_book.html
{% include "menu.html" %}
<html>
    <head>
        <title>Livre</title>
    </head>
    <body>
        {% load crispy_forms_tags %}  
        <div class="container">
            <div class="row">
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="col-md-12">
                    <h1>Ajouter un livre</h1>
                    <div class="form-group">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input class="btn btn-success" type="submit" value="Ajouter">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

members/templates/my_library/add_club.html
{% include "menu.html" %}
<html>
    <head>
        <title>Club</title>
    </head>
    <body>
        {% load crispy_forms_tags %}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Ajouter un club</h1>
                    <div class="form-group">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input class="btn btn-success" type="submit" value="Ajouter">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

members/templates/my_library/edit_club.html
{% include "menu.html" %}
<html>
    <head>
        <title>Club</title>
    </head>
    <body>
        <h1>Modifier un club</h1>
        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Ajouter">
        </form>
    </body>
</html>

members/templates/my_library/index.html
{% include "menu.html" %}
<html>
    <head>
        <title>Ma librairie</title>
    </head>
    <body>
        <h1>Liste des livres de la librairie</h1>
        <a class="btn btn-secondary" href="{% url 'members:add_book' %}">Ajouter un livre</a>
        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th>Cover</th>
                    <th>Titre</th>
                    <th>Auteur</th>
                    <th>Description</th>
                    <th>Editeur</th>
                    <th>Collection</th>
                    <th>Catégorie</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% if books|length > 0 %}
                {% for book in books %}
                <tr>
                    {% if book.cover %}
                    <td><img src="{{ book.cover.url }}" alt="Image du livre" class="img-thumbnail" style="max-width: 150px;"></td>
                    {% else %}
                        <td><img src="/covers/default.jpg" alt="Image du livre" class="img-thumbnail" style="max-width: 150px;"></td>
                    {% endif %}
                    <td>{{ book.title }}</td>
                    <td>{{ book.author.name }}</td>
                    <td>{{ book.description }}</td>
                    <td>{{ book.editor.name }}</td>
                    <td>{{ book.collection.name }}</td>
                    <td>{{ book.category.name }}</td>
                    <td>
                        <a href="">Modifier</a>
                        <a href="">Supprimer</a>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="2">Aucun livre</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </body>
</html>

members/templates/my_library/informations.html
{% include "menu.html" %}
<html>
    <head>
        <title>Informations</title>
    </head>
    <body>
        <h1>Listes des informations disponibles pour les livres</h1>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <h2>Auteurs</h2>
                    <ul>
                        {% for author in authors %}
                            <li>{{ author.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-6">
                    <h2>Catégories</h2>
                    <ul>
                        {% for category in categories %}
                            <li>{{ category.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <h2>Editeurs</h2>
                    <ul>
                        {% for editor in editors %}
                            <li>{{ editor.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-6">
                    <h2>Collections</h2>
                    <ul>
                        {% for collection in collections %}
                            <li>{{ collection.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>

members/templates/my_library/show_club.html
{% include "menu.html" %}
{% load i18n %}
<html>
    <head>
        <title>Club</title>
    </head>
    <body>
        <h1>Fiche du club</h1>
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">{{ club.name }}</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-9">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Calendrier des sessions</h5>
                        <p class="card-text">
                            <div class="col-12">
                                <div id="calendar"></div>
                            </div>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="card-body">
                    <h3>Informations</h3>
                    <h5>Créé le {% language 'fr' %} {{ club.created_at|date:"d F Y" }} {% endlanguage %}</h5>
                    <h5>Nombre de membres : {{ club.members_count }}/{{ club.capacity }}</h5>
                    <h5>Livre : {{ club.book.title }}</h5>
                    <p class="card-text">{{ club.description }}</p>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Ajouter une session</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <table>
                            {{ form.as_p }}
                            {{ form.media }}
                        </table>
                        <input class="btn btn-secondary" type="submit" value="Ajouter">
                    </form>
                </div>
            </div>
            <div class="col-9">
                <div class="card-body">
                    <h5 class="card-title">Liste des membres</h5>
                    <table class="table table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Mail</th>
                                <th>Date d'entrée</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% if members|length > 0 %}
                            {% for member in members %}
                            <tr>
                                <td>{{ member.user.username }}</td>
                                <td>{{ member.user.email }}</td>
                                <td>{{ member.created_at }}</td>
                                <td>
                                    <a class="btn btn-danger" href="{% url 'members:delete_member' member.id %}">Supprimer</a>
                                </td>
                            </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td class="text-center" colspan="2">Aucun membre</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.0.2/index.global.min.js"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var calendarEl = document.getElementById('calendar');
                var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                height: 'auto',
                contentHeight: 'auto',
                locale: 'fr',
                buttonText: {
                    today: "Aujourd'hui",
                },
                eventSources: [
                    {{ sessions_in_calendar|safe }}
                ],
                displayEventTime: false,
                eventClick: function(info) {
                    window.location = info.event.url;
                },
            });
            
            calendar.render();
            });
            
        </script>
    </body>
</html>

members/templates/my_library/show_session.html
{% include "menu.html" %}
{% load i18n %}
<html>
    <head>
        <title>Session</title>
    </head>
    <body>
        <h1>Fiche de la session</h1>
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">{{ session.date }}</h2>
                <a class="btn btn-danger" href="{% url 'members:delete_session' session.id %}">Supprimer la session</a>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    {% for participant in participants %}
                    <li class="list-group-item">
                        {{ participant.user.username }}
                        <a class="btn btn-danger" href="{% url 'members:delete_participant' participant.id %}">Supprimer</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </body>
</html>