books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.book_index , name='books'),

    path('detail_book/<int:id>', views.detail_book, name='detail_book'),
]

clubs/urls.py
from django.urls import path
from . import views

app_name = 'clubs'

urlpatterns = [
    path('clubs/', views.club_index , name='clubs'),
    path('clubs/<int:club_id>', views.detail_club, name='detail_club'),
]

home/urls.py
from django.urls import path, include
from .views import home_index

urlpatterns = [
    path('', home_index, name='home-index'),
]

libraries/urls.py
from django.urls import path
from . import views
from djgeojson.views import GeoJSONLayerView
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .models import Library

app_name = 'libraries'

urlpatterns = [
    path('', views.libraries, name='libraries'),
    path('libraries/', views.library_index, name='library_index'),
    url(r'^data.geojson$', GeoJSONLayerView.as_view(model=Library, properties=('slug', 'name', 'description', 'arr')), name='data'),

    path('libraries/<str:slug>', views.library_detail, name='library_detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('board/', include('board.urls')),
    path('misc/', include('misc.urls')),
    path('libraries/', include('libraries.urls')),
    path('books/', include('books.urls')),
    path('clubs/', include('clubs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('my_profile/<str:username>', views.my_profile, name='user_profile'),
    path('login_user/', views.login_user, name='login'),
    path('logout_user/', views.logout_user, name='logout'),
    path('register_user/', views.register_user, name='register'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_books/', views.my_books, name='user_books'),
    path('my_books/add/<str:reference>', views.add_overdue, name='add_overdue'),
    path('my_books/giveback/<str:reference>', views.edit_overdue, name='edit_overdue'),
    path('my_clubs/', views.my_clubs, name='user_clubs'),
    path('my_clubs/join/<int:club_id>', views.join_club, name='join_club'),
    path('my_clubs/leave/<int:club_id>', views.leave_club, name='leave_club'),
    path('my_sessions/join/<int:session_id>', views.join_session, name='join_session'),
    path('my_sessions/leave/<int:session_id>', views.leave_session, name='leave_session'),

    path('my_library/', views.my_library, name='user_library'),
    path('informations/', views.informations, name='informations'),
    path('add_book/', views.add_book, name='add_book'),

    path('clubs/<int:club_id>', views.show_club, name='show_club'),
    path('clubs/add', views.add_club, name='add_club'),

    path('members/delete/<int:member_id>', views.delete_member, name='delete_member'),

    path('sessions/<int:session_id>', views.show_session, name='show_session'),
    path('sessions/<int:club_id>/add', views.show_session, name='add_session'),
    path('sessions/<int:session_id>/delete', views.delete_session, name='delete_session'),

    path('participants/delete/<int:participant_id>', views.delete_participant, name='delete_participant')
]

misc/urls.py
from django.urls import path
from . import views

app_name = 'misc'

urlpatterns = [
]

misc/models.py
from django.db import models

# Create your models here.

misc/views.py
from django.shortcuts import render

# Create your views here.

misc/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Library - {% block title %}{% endblock %}</title>
  </head>

  <body>
    {% include "menu.html" %}

    <div id="content">
      {% load i18n %}
      {% language 'fr' %}
      {% block content %}
      {% endblock %}
      {% endlanguage %}
    </div>

    {% block javascript %}{% endblock %}
  </body>
</html>

misc/templates/menu.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Librairie</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'books:books' %}">Liste des livres</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'libraries:library_index' %}">Liste des librairies</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/libraries/">Trouver une librairie</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'clubs:clubs' %}">Liste des clubs</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/board/">Forum</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'members:logout' %}">Se déconnecter</a>
      </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'members:login' %}">Connexion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'members:register' %}">S'enregistrer</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% if user.is_authenticated %}
  {% include "sidebar.html" %}
{% endif %}

misc/templates/sidebar.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% if user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <a class="navbar-brand" href="{% url 'members:dashboard' %}">Interface libraire</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav2" aria-controls="navbarNav2"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav2">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:user_library' %}">Livres de la librairie</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:informations' %}">Informations</a>
            </li>
        </ul>
    </div>
</nav>
{% else %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <a class="navbar-brand" href="{% url 'members:dashboard' %}">Mon interface</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav3" aria-controls="navbarNav3"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav3">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:user_profile' user.username %}">Mon profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:user_books' %}">Mes livres</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:user_clubs' %}">Mes groupes de lectures</a>
            </li>
        </ul>
    </div>
</nav>
{% endif %}